<a href="https://colab.research.google.com/github/wmxof/DL_from_Scratch/blob/main/DL_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**numpy 라이브러리**  
================================
#      
#  
numpy 라이브러리 import

In [ ]:
import numpy as np

###**numpy 1차원 배열 생성 : np.array()**
---------------------------------------------------

> 리스트를 인수로 받아 배열로 반환.

> 이때, 파라미터(인자) 값으로 배열 및 상수를 넘길 수 있음.


*   파라미터 배열 : n차원 형태의 배열 반환.



```
np.array([1,2],[3,4,5],[6,7])
```


*   파라미터 상수(1차원 리스트) : 1차원 형태의 배열 반환.  <br/>



```
np.array(0)
np.array([1,3,4])
```



In [ ]:
x = np.array([1.0, 2.0, 3.0])

print(x)
type(x)

[1. 2. 3.]


numpy.ndarray

###**넘파이의 산술 연산**    
---------------------------------------------------
  
브로드캐스트 : 스칼라값과의 계산이 넘파이 배열의 원소별로 한 번씩 수행되는 것.

In [ ]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])

print(x+y)
print(x-y)
print(x*y)
print(x/y)

[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]


###**브로드캐스트**
---------------------------------------------------
#  
브로드캐스트는 스칼라값 뿐만 아니라,  
서로 다른 차원의 배열끼리도 계산이 가능하다.  
#  
**단, 차원의 짝이 맞을 때,  
즉 한 배열을 곱해서 다른 배열 크기로 만들 수 있을 때만 사용 가능하다.**

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[10, 20]])

print(A*B)

[[10 40]
 [30 80]]


###**원소 접근**
---------------------------------------------------
#  
일반 배열처럼 0부터 인덱스에 접근할 수 있다.  
혹은 for문으로 접근 가능하다.

In [ ]:
A = np.array([[51, 55], [14, 19], [0, 4]])

print(A[0])
print(A[0][1])

for row in A:
  print(row)

[51 55]
55
[51 55]
[14 19]
[0 4]


###**알아두면 좋은 함수**
---------------------------------------------------
#  
>.flatten() : N차원 배열 A를 1차원 배열로 변환하는 함수
```
A = A.flatten()
print(A)
```
#  
>A[np.array([])] : 이미 존재하는 배열과 함께 np.array 사용 시, np.array의 파라미터 값의 A의 원소 출력
```
A[np.array([0, 2, 4)]
```
또한, 위 방법으로 일정 이상의 값만 받아올 수 있다.
```
A[A>15]
```

In [ ]:
A = np.array([[51, 55], [14, 19], [0, 4]])
print(A)
A = A.flatten()
print()
print("A.flatten() : ", A)
print("A[np.array([])] 활용: ",A[np.array([0, 2, 4])])
print(A[A>15])

[[51 55]
 [14 19]
 [ 0  4]]

A.flatten() :  [51 55 14 19  0  4]
A[np.array([])] 활용:  [51 14  0]
[51 55 19]
